version: '3.8'

services:
  lightrag:
    container_name: lightrag_api_only
    # 如果你想重新 build image，請取消註解下面兩行
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: ghcr.io/hkuds/lightrag:latest
    ports:
      # 前面是你主機對外的 Port (9622)，後面是容器內部的 Port (9621)
      - "9622:9621" 
    
    volumes:
      - ./data/rag_storage:/app/data/rag_storage
      - ./data/inputs:/app/data/inputs
      - ./data/mineru_models:/app/data/mineru_models
      - ./config.ini:/app/config.ini
      - ./.env:/app/.env

    environment:
      - MINERU_MODEL_DIR=/app/data/mineru_models
      - WORKERS=1
      - TIMEOUT=1800

    networks:
      - ai_network

networks:
  ai_network:
    driver: bridge